language: python
python:
 - "2.7"

# Install all dependencies
install:
 - pip install -r requirements.txt
 - pip install coverage

# Run all tests
script:
 - nosetests --with-coverage --cover-erase --cover-package=HboMovieData
