language: python
python:
 - "2.7"

# Install all dependencies
install: "pip install -r requirements.txt"

# Run all tests
#script: "nosetests --with-coverage --cover-package=HboMovieData"
script: nosetests
