language: python
python:
 - "2.7"

# Install all dependencies
install:
 - pip install python-coveralls
 - pip install coverage
 - pip install -r requirements.txt

# Run all tests
script:
 - nosetests --with-coverage --cover-erase

after_success:
 - coveralls
